services:
  gcs-nginx:
    image: nginx:latest
    container_name: gcs-nginx
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - ${FRONT_END_REVERSE_PROXY_PORT}:443
    depends_on:
      - gcs
    environment:
      FRONT_END_REVERSE_PROXY_PORT: ${FRONT_END_REVERSE_PROXY_PORT}
  gcs-postgres:
    image: postgres:14
    container_name: gcs-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - gcs-postgres-data:/var/lib/postgresql/data
      - ${DATABASE_INIT_SCRIPT_PATH}:/docker-entrypoint-initdb.d
  gcs-redis:
    image: redis:latest
    container_name: gcs-redis
    restart: always
  gcs:
    container_name: gcs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_MAIN_GROUP: ${GIT_USER_MAIN_GROUP}
        GIT_USER_PASSWORD: ${GIT_USER_PASSWORD}
        GIT_USER_HOME: ${GIT_USER_HOME}
        GITOLITE_REPOSITORY: ${GITOLITE_REPOSITORY}
        GITOLITE_INSTALLATION_DIR: ${GITOLITE_INSTALLATION_DIR}
        GITOLITE_ADMIN_REPOSITORY: ${GITOLITE_ADMIN_REPOSITORY}
        GITOLITE_ADMIN_REPOSITORY_USER_NAME: ${GITOLITE_ADMIN_REPOSITORY_USER_NAME}
        GITOLITE_ADMIN_REPOSITORY_USER_EMAIL: ${GITOLITE_ADMIN_REPOSITORY_USER_EMAIL}
        JAVA_WORKING_DIRECTORY: ${JAVA_WORKING_DIRECTORY}
        GITOLITE_PATH: ${GITOLITE_PATH}
        TARGET_JAR_PATH: ${TARGET_JAR_PATH}
    volumes:
      - gcs-user-repositories:${GITOLITE_USER_REPOSITORIES}
    ports:
      - ${GCS_SPRING_MAPPING_PORT}:8080
      - ${GCS_SSH_MAPPING_PORT}:22
    
    depends_on:
      - gcs-postgres
      - gcs-redis
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DRUID_USERNAME: ${SPRING_DRUID_USERNAME}
      SPRING_DRUID_PASSWORD: ${SPRING_DRUID_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROTOCOL: ${SPRING_MAIL_PROTOCOL}
      SPRING_MAIL_DEFAULT_ENCODING: ${SPRING_MAIL_DEFAULT_ENCODING}
      GIT_SERVER_DOMAIN: ${GIT_SERVER_DOMAIN}
      GIT_SERVER_PORT: ${GIT_SERVER_PORT}
      GIT_SERVER_USERNAME: ${GIT_SERVER_USERNAME}
      GIT_SERVER_HOME: ${GIT_SERVER_HOME}
      GIT_SERVER_ADMIN_REPOSITORY: ${GIT_SERVER_ADMIN_REPOSITORY}
      MD5_SALT: ${MD5_SALT}
      JWT_SECRET: ${JWT_SECRET}
      GCS_LOGGING_DIRECTORY: ${GCS_LOGGING_DIRECTORY}
      GCS_LOGGING_FILE_MAX_SIZE: ${GCS_LOGGING_FILE_MAX_SIZE}
      GCS_LOGGING_MAX_HISTORY: ${GCS_LOGGING_MAX_HISTORY}
      GCS_LOGGING_TOTAL_SIZE_CAP: ${GCS_LOGGING_TOTAL_SIZE_CAP}
volumes:
  gcs-postgres-data:
  gcs-user-repositories:
