name: Google Java Style Format

on:
  pull_request:
    branches: 
      - master

jobs:
  java-formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up openjdk-17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Format
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--replace --aosp"
          skip-commit: true

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply Google Java Style Format"
