name: Maven Test
on:
  workflow_run:
    workflows: ["Google Java Style Format"]
    types:
      - completed

jobs:
  maven-test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Preparation
        run: |
          bash prepare_dev.sh postgres
      - name: Maven Test
        run: |
          mvn test
