name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build as a tar.gz
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup jdk17 and maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 17
          checkout-submodules: true

      - name: Build jar package
        run: mvn clean package -Dmaven.test.skip=true

      - name: Tar as a gcs-back-end.tar.gz
        run: tar -czf gcs-back-end.tar.gz target/gcs-back-end.jar .env Dockerfile docker-compose.yml 3rdparty/gitolite database/init nginx

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gcs-back-end
          path: gcs-back-end.tar.gz

  release:
    name: Release to GitHub
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: gcs-back-end

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ github.token }}
          files: gcs-back-end.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
